### ISSUE TITLE
thanks for providing a js version of fastembed 

### ISSUE THREAD

**Issue by kindziora** [Anush008/fastembed-js#13]
would this work in the browser ?

**Comment by Anush008** [comment]
No.

**Comment by kindziora** [comment]
so switching to onnxruntime-web is not enough i guess :( , can you explain what the major changes would be to have this in the browser?
Kind regards

**Comment by Anush008** [comment]
I haven't really tried onnxruntime-web. So I am not sure.

**Comment by kindziora** [comment]
ok thanks!
