### ISSUE TITLE
@anush008/tokenizers does not support Linux-ARM

### ISSUE THREAD

**Issue by elkay** [Anush008/fastembed-js#15]
Without ARM support, fastembed-js won't run on newer AWS t4g EC2 instances. Runs fine on x86 instances.

Error: Cannot find module '@anush008/tokenizers-linux-arm64-gnu'

Any thoughts on a way around this?

**Comment by Anush008** [comment]
Hi @elkay. I'm working on a prototype that you might fight interesting.

Can you try

```javascript
import { sum, TextEmbedding, EmbeddingModel } from 'fasterembed'

  const model = new TextEmbedding(EmbeddingModel.AllMiniLML6V2);


  let documents = [
    "passage: Hello, World!",
    "query: Hello, World!",
    "passage: This is an example passage.",
    // You can leave out the prefix but it's recommended
    "fastembed-js is licensed under MIT"
  ];


  const embeddings = model.embed(documents, 2);
````

**Comment by Anush008** [comment]
After installing using

```bash
npm install fasterembed
```

**Comment by Anush008** [comment]
Oh bummer.

Supports the following architectures.

https://github.com/Anush008/fasterembed/tree/main/npm

**Comment by elkay** [comment]
> Oh bummer.
> 
> Supports the following architectures.
> 
> https://github.com/Anush008/fasterembed/tree/main/npm

Yeah, that's this issue I was reporting haha. No Linux ARM. So I guess no workaround right now?

**Comment by Anush008** [comment]
If I remember correctly, I removed arm64-linux because it was failing the Fasterembed unit test.

I'll try if I can include it back.

**Comment by elkay** [comment]
Ok cool, thanks! :-) The AWS t4g offerings are their modern EC2 offerings and both cost less and outperform their predecessors, so it would be great to be able to migrate my project over to them.

**Comment by elkay** [comment]
Hey just an FYI, when I see builds for those servers it's specifically "aarch64" support. Not sure if there is a difference, maybe not, but thought I would clarify.

**Comment by Anush008** [comment]
Closing since stale.

**Comment by Anush008** [comment]
Nope. No new version of https://github.com/huggingface/tokenizers Node bindings has been released with support for Linux ARM.

**Comment by Anush008** [comment]
I suggest you try https://www.npmjs.com/package/@xenova/transformers

**Comment by jmikedupont2** [comment]
so we need to port transformers first?

**Comment by jmikedupont2** [comment]
https://github.com/huggingface/tokenizers/tree/main/bindings/node/npm/linux-arm64-gnu it appears that it  is here

**Comment by jmikedupont2** [comment]
https://github.com/Anush008/tokenizers/pull/2 here is my patch!

**Comment by jmikedupont2** [comment]
https://github.com/Anush008/fastembed-js/pull/25
