### ISSUE TITLE
Config file not found at local_cache\fast-bge-small-en\config.json

### ISSUE THREAD

**Issue by ItsAnoch** [Anush008/fastembed-js#17]
Can't seem to figure out why the config.json and the tokenizer_config.json don't seem to be downloaded.

OS: Windows 11
Runtime: Bun 1.1.6

```
import { EmbeddingModel, FlagEmbedding } from "fastembed";

const embeddingModel = await FlagEmbedding.init({
    model: EmbeddingModel.BGESmallEN
});

// ....
```

**Comment by Anush008** [comment]
Could you elaborate? Are there any error messages?

**Comment by ItsAnoch** [comment]
Yes. Sorry for the late response.

error: Config file not found at local_cache\fast-bge-base-en\config.json

**Comment by Anush008** [comment]
Please try deleting the FastEmbed cache directory.
