### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by hadupa** [Anush008/fastembed-js#22]
I'm using this as an alternative to qdrant python and am using it as an example. Unfortunately, when I try this I keep getting a typeError when sending to qdrant. I went into the code with my debugger and discovered that this code is creating a different object than qdrant's python does.

For example, I am currently getting this error:

Error: Expected value of type vector but got undefined.

Is this an error in the code or in my implementation?

**Comment by Anush008** [comment]
Can you log the return value from FastEmbed-js?

**Comment by hadupa** [comment]
Sure thing, here it is along with the error:

Received POST request for /fastembed
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
{
  message: 'hey wake up now',
  embedding: [
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0,
    ... 284 more items
  ]
}

**Comment by Anush008** [comment]
I mean if the return value from the `embed()` method of FastEmbed-js is running fine, it must be something else in your code that's causing this.
