### ISSUE TITLE
Model Type

### ISSUE THREAD

**Issue by msj121** [Anush008/fastembed-js#8]
Is it possible to use "multi-qa-MiniLM-L6-cos-v1" for fast embed or no?

**Comment by Anush008** [comment]
Hey @msj121. Thanks for reaching out.
This library intends to maintain parity with the original implementation.

You can raise an issue at https://github.com/qdrant/fastembed/issues for the addition of the model, if done, it will be reflected here as well.

**Comment by msj121** [comment]
Wow that was lightning fast! Ok - asked there, hopefully will figure this one out. Thanks!
